/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as BusinessIndexRouteImport } from './routes/business.index'
import { Route as CallIdRouteImport } from './routes/call.$id'
import { Route as CallsIndexRouteImport } from './routes/calls.index'
import { Route as CatalogIndexRouteImport } from './routes/catalog.index'
import { Route as CatalogIdRouteImport } from './routes/catalog.$id'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as ChatIdRouteImport } from './routes/chat.$id'
import { Route as ContactsIndexRouteImport } from './routes/contacts.index'
import { Route as ContactsAddRouteImport } from './routes/contacts.add'
import { Route as FinanceIndexRouteImport } from './routes/finance.index'
import { Route as LedgerIndexRouteImport } from './routes/ledger.index'
import { Route as LedgerIdRouteImport } from './routes/ledger.$id'
import { Route as PhotoNewRouteImport } from './routes/photo.new'
import { Route as PrepareTokenRouteImport } from './routes/prepare.$token'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as TasksIdRouteImport } from './routes/tasks.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessIndexRoute = BusinessIndexRouteImport.update({
  id: '/business/',
  path: '/business/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallIdRoute = CallIdRouteImport.update({
  id: '/call/$id',
  path: '/call/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsIndexRoute = CallsIndexRouteImport.update({
  id: '/calls/',
  path: '/calls/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIdRoute = CatalogIdRouteImport.update({
  id: '/catalog/$id',
  path: '/catalog/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsIndexRoute = ContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsAddRoute = ContactsAddRouteImport.update({
  id: '/contacts/add',
  path: '/contacts/add',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerIndexRoute = LedgerIndexRouteImport.update({
  id: '/ledger/',
  path: '/ledger/',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerIdRoute = LedgerIdRouteImport.update({
  id: '/ledger/$id',
  path: '/ledger/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoNewRoute = PhotoNewRouteImport.update({
  id: '/photo/new',
  path: '/photo/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PrepareTokenRoute = PrepareTokenRouteImport.update({
  id: '/prepare/$token',
  path: '/prepare/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIdRoute = TasksIdRouteImport.update({
  id: '/tasks/$id',
  path: '/tasks/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/call/$id': typeof CallIdRoute
  '/catalog/$id': typeof CatalogIdRoute
  '/chat/$id': typeof ChatIdRoute
  '/contacts/add': typeof ContactsAddRoute
  '/ledger/$id': typeof LedgerIdRoute
  '/photo/new': typeof PhotoNewRoute
  '/prepare/$token': typeof PrepareTokenRoute
  '/tasks/$id': typeof TasksIdRoute
  '/business/': typeof BusinessIndexRoute
  '/calls/': typeof CallsIndexRoute
  '/catalog/': typeof CatalogIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/contacts/': typeof ContactsIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/ledger/': typeof LedgerIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/call/$id': typeof CallIdRoute
  '/catalog/$id': typeof CatalogIdRoute
  '/chat/$id': typeof ChatIdRoute
  '/contacts/add': typeof ContactsAddRoute
  '/ledger/$id': typeof LedgerIdRoute
  '/photo/new': typeof PhotoNewRoute
  '/prepare/$token': typeof PrepareTokenRoute
  '/tasks/$id': typeof TasksIdRoute
  '/business': typeof BusinessIndexRoute
  '/calls': typeof CallsIndexRoute
  '/catalog': typeof CatalogIndexRoute
  '/chat': typeof ChatIndexRoute
  '/contacts': typeof ContactsIndexRoute
  '/finance': typeof FinanceIndexRoute
  '/ledger': typeof LedgerIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/tasks': typeof TasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/call/$id': typeof CallIdRoute
  '/catalog/$id': typeof CatalogIdRoute
  '/chat/$id': typeof ChatIdRoute
  '/contacts/add': typeof ContactsAddRoute
  '/ledger/$id': typeof LedgerIdRoute
  '/photo/new': typeof PhotoNewRoute
  '/prepare/$token': typeof PrepareTokenRoute
  '/tasks/$id': typeof TasksIdRoute
  '/business/': typeof BusinessIndexRoute
  '/calls/': typeof CallsIndexRoute
  '/catalog/': typeof CatalogIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/contacts/': typeof ContactsIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/ledger/': typeof LedgerIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/register'
    | '/support'
    | '/terms'
    | '/call/$id'
    | '/catalog/$id'
    | '/chat/$id'
    | '/contacts/add'
    | '/ledger/$id'
    | '/photo/new'
    | '/prepare/$token'
    | '/tasks/$id'
    | '/business/'
    | '/calls/'
    | '/catalog/'
    | '/chat/'
    | '/contacts/'
    | '/finance/'
    | '/ledger/'
    | '/profile/'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/register'
    | '/support'
    | '/terms'
    | '/call/$id'
    | '/catalog/$id'
    | '/chat/$id'
    | '/contacts/add'
    | '/ledger/$id'
    | '/photo/new'
    | '/prepare/$token'
    | '/tasks/$id'
    | '/business'
    | '/calls'
    | '/catalog'
    | '/chat'
    | '/contacts'
    | '/finance'
    | '/ledger'
    | '/profile'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/register'
    | '/support'
    | '/terms'
    | '/call/$id'
    | '/catalog/$id'
    | '/chat/$id'
    | '/contacts/add'
    | '/ledger/$id'
    | '/photo/new'
    | '/prepare/$token'
    | '/tasks/$id'
    | '/business/'
    | '/calls/'
    | '/catalog/'
    | '/chat/'
    | '/contacts/'
    | '/finance/'
    | '/ledger/'
    | '/profile/'
    | '/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  CallIdRoute: typeof CallIdRoute
  CatalogIdRoute: typeof CatalogIdRoute
  ChatIdRoute: typeof ChatIdRoute
  ContactsAddRoute: typeof ContactsAddRoute
  LedgerIdRoute: typeof LedgerIdRoute
  PhotoNewRoute: typeof PhotoNewRoute
  PrepareTokenRoute: typeof PrepareTokenRoute
  TasksIdRoute: typeof TasksIdRoute
  BusinessIndexRoute: typeof BusinessIndexRoute
  CallsIndexRoute: typeof CallsIndexRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ContactsIndexRoute: typeof ContactsIndexRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
  LedgerIndexRoute: typeof LedgerIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/': {
      id: '/business/'
      path: '/business'
      fullPath: '/business/'
      preLoaderRoute: typeof BusinessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call/$id': {
      id: '/call/$id'
      path: '/call/$id'
      fullPath: '/call/$id'
      preLoaderRoute: typeof CallIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls/': {
      id: '/calls/'
      path: '/calls'
      fullPath: '/calls/'
      preLoaderRoute: typeof CallsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/$id': {
      id: '/catalog/$id'
      path: '/catalog/$id'
      fullPath: '/catalog/$id'
      preLoaderRoute: typeof CatalogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/': {
      id: '/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof ContactsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/add': {
      id: '/contacts/add'
      path: '/contacts/add'
      fullPath: '/contacts/add'
      preLoaderRoute: typeof ContactsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/': {
      id: '/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger/': {
      id: '/ledger/'
      path: '/ledger'
      fullPath: '/ledger/'
      preLoaderRoute: typeof LedgerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger/$id': {
      id: '/ledger/$id'
      path: '/ledger/$id'
      fullPath: '/ledger/$id'
      preLoaderRoute: typeof LedgerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo/new': {
      id: '/photo/new'
      path: '/photo/new'
      fullPath: '/photo/new'
      preLoaderRoute: typeof PhotoNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prepare/$token': {
      id: '/prepare/$token'
      path: '/prepare/$token'
      fullPath: '/prepare/$token'
      preLoaderRoute: typeof PrepareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$id': {
      id: '/tasks/$id'
      path: '/tasks/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof TasksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  CallIdRoute: CallIdRoute,
  CatalogIdRoute: CatalogIdRoute,
  ChatIdRoute: ChatIdRoute,
  ContactsAddRoute: ContactsAddRoute,
  LedgerIdRoute: LedgerIdRoute,
  PhotoNewRoute: PhotoNewRoute,
  PrepareTokenRoute: PrepareTokenRoute,
  TasksIdRoute: TasksIdRoute,
  BusinessIndexRoute: BusinessIndexRoute,
  CallsIndexRoute: CallsIndexRoute,
  CatalogIndexRoute: CatalogIndexRoute,
  ChatIndexRoute: ChatIndexRoute,
  ContactsIndexRoute: ContactsIndexRoute,
  FinanceIndexRoute: FinanceIndexRoute,
  LedgerIndexRoute: LedgerIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
