/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as BusinessIndexRouteImport } from './routes/business.index'
import { Route as CallIdRouteImport } from './routes/call.$id'
import { Route as CallsIndexRouteImport } from './routes/calls.index'
import { Route as CallsIdRouteImport } from './routes/calls.$id'
import { Route as CatalogIndexRouteImport } from './routes/catalog.index'
import { Route as CatalogIdRouteImport } from './routes/catalog.$id'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as ChatIdRouteImport } from './routes/chat.$id'
import { Route as ContactsIndexRouteImport } from './routes/contacts.index'
import { Route as ContactsIdRouteImport } from './routes/contacts.$id'
import { Route as ContactsAddRouteImport } from './routes/contacts.add'
import { Route as FinanceIndexRouteImport } from './routes/finance.index'
import { Route as LedgerIndexRouteImport } from './routes/ledger.index'
import { Route as LedgerIdRouteImport } from './routes/ledger.$id'
import { Route as PhotoNewRouteImport } from './routes/photo.new'
import { Route as PrepareTokenRouteImport } from './routes/prepare.$token'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as SettingsCallsRouteImport } from './routes/settings.calls'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as SettingsVoiceRouteImport } from './routes/settings.voice'
import { Route as StatusIndexRouteImport } from './routes/status.index'
import { Route as StatusNewRouteImport } from './routes/status.new'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as TasksIdRouteImport } from './routes/tasks.$id'
import { Route as CallPrepareConversationIdRouteImport } from './routes/call.prepare.$conversationId'
import { Route as ApiPublicPushActionsRouteImport } from './routes/api/public/push/actions'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessIndexRoute = BusinessIndexRouteImport.update({
  id: '/business/',
  path: '/business/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallIdRoute = CallIdRouteImport.update({
  id: '/call/$id',
  path: '/call/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsIndexRoute = CallsIndexRouteImport.update({
  id: '/calls/',
  path: '/calls/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsIdRoute = CallsIdRouteImport.update({
  id: '/calls/$id',
  path: '/calls/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIdRoute = CatalogIdRouteImport.update({
  id: '/catalog/$id',
  path: '/catalog/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsIndexRoute = ContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsIdRoute = ContactsIdRouteImport.update({
  id: '/contacts/$id',
  path: '/contacts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsAddRoute = ContactsAddRouteImport.update({
  id: '/contacts/add',
  path: '/contacts/add',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerIndexRoute = LedgerIndexRouteImport.update({
  id: '/ledger/',
  path: '/ledger/',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerIdRoute = LedgerIdRouteImport.update({
  id: '/ledger/$id',
  path: '/ledger/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoNewRoute = PhotoNewRouteImport.update({
  id: '/photo/new',
  path: '/photo/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PrepareTokenRoute = PrepareTokenRouteImport.update({
  id: '/prepare/$token',
  path: '/prepare/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsCallsRoute = SettingsCallsRouteImport.update({
  id: '/settings/calls',
  path: '/settings/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/settings/notifications',
  path: '/settings/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsVoiceRoute = SettingsVoiceRouteImport.update({
  id: '/settings/voice',
  path: '/settings/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusIndexRoute = StatusIndexRouteImport.update({
  id: '/status/',
  path: '/status/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusNewRoute = StatusNewRouteImport.update({
  id: '/status/new',
  path: '/status/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIdRoute = TasksIdRouteImport.update({
  id: '/tasks/$id',
  path: '/tasks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CallPrepareConversationIdRoute =
  CallPrepareConversationIdRouteImport.update({
    id: '/call/prepare/$conversationId',
    path: '/call/prepare/$conversationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPushActionsRoute = ApiPublicPushActionsRouteImport.update({
  id: '/api/public/push/actions',
  path: '/api/public/push/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/delete-account': typeof DeleteAccountRoute
  '/download': typeof DownloadRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/premium': typeof PremiumRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/call/$id': typeof CallIdRoute
  '/calls/$id': typeof CallsIdRoute
  '/catalog/$id': typeof CatalogIdRoute
  '/chat/$id': typeof ChatIdRoute
  '/contacts/$id': typeof ContactsIdRoute
  '/contacts/add': typeof ContactsAddRoute
  '/ledger/$id': typeof LedgerIdRoute
  '/photo/new': typeof PhotoNewRoute
  '/prepare/$token': typeof PrepareTokenRoute
  '/settings/calls': typeof SettingsCallsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/voice': typeof SettingsVoiceRoute
  '/status/new': typeof StatusNewRoute
  '/tasks/$id': typeof TasksIdRoute
  '/business/': typeof BusinessIndexRoute
  '/calls/': typeof CallsIndexRoute
  '/catalog/': typeof CatalogIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/contacts/': typeof ContactsIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/ledger/': typeof LedgerIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/status/': typeof StatusIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/call/prepare/$conversationId': typeof CallPrepareConversationIdRoute
  '/api/public/push/actions': typeof ApiPublicPushActionsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/delete-account': typeof DeleteAccountRoute
  '/download': typeof DownloadRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/premium': typeof PremiumRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/call/$id': typeof CallIdRoute
  '/calls/$id': typeof CallsIdRoute
  '/catalog/$id': typeof CatalogIdRoute
  '/chat/$id': typeof ChatIdRoute
  '/contacts/$id': typeof ContactsIdRoute
  '/contacts/add': typeof ContactsAddRoute
  '/ledger/$id': typeof LedgerIdRoute
  '/photo/new': typeof PhotoNewRoute
  '/prepare/$token': typeof PrepareTokenRoute
  '/settings/calls': typeof SettingsCallsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/voice': typeof SettingsVoiceRoute
  '/status/new': typeof StatusNewRoute
  '/tasks/$id': typeof TasksIdRoute
  '/business': typeof BusinessIndexRoute
  '/calls': typeof CallsIndexRoute
  '/catalog': typeof CatalogIndexRoute
  '/chat': typeof ChatIndexRoute
  '/contacts': typeof ContactsIndexRoute
  '/finance': typeof FinanceIndexRoute
  '/ledger': typeof LedgerIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/status': typeof StatusIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/call/prepare/$conversationId': typeof CallPrepareConversationIdRoute
  '/api/public/push/actions': typeof ApiPublicPushActionsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/delete-account': typeof DeleteAccountRoute
  '/download': typeof DownloadRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/premium': typeof PremiumRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/call/$id': typeof CallIdRoute
  '/calls/$id': typeof CallsIdRoute
  '/catalog/$id': typeof CatalogIdRoute
  '/chat/$id': typeof ChatIdRoute
  '/contacts/$id': typeof ContactsIdRoute
  '/contacts/add': typeof ContactsAddRoute
  '/ledger/$id': typeof LedgerIdRoute
  '/photo/new': typeof PhotoNewRoute
  '/prepare/$token': typeof PrepareTokenRoute
  '/settings/calls': typeof SettingsCallsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/voice': typeof SettingsVoiceRoute
  '/status/new': typeof StatusNewRoute
  '/tasks/$id': typeof TasksIdRoute
  '/business/': typeof BusinessIndexRoute
  '/calls/': typeof CallsIndexRoute
  '/catalog/': typeof CatalogIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/contacts/': typeof ContactsIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/ledger/': typeof LedgerIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/status/': typeof StatusIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/call/prepare/$conversationId': typeof CallPrepareConversationIdRoute
  '/api/public/push/actions': typeof ApiPublicPushActionsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/delete-account'
    | '/download'
    | '/home'
    | '/login'
    | '/onboarding'
    | '/premium'
    | '/privacy'
    | '/register'
    | '/support'
    | '/terms'
    | '/call/$id'
    | '/calls/$id'
    | '/catalog/$id'
    | '/chat/$id'
    | '/contacts/$id'
    | '/contacts/add'
    | '/ledger/$id'
    | '/photo/new'
    | '/prepare/$token'
    | '/settings/calls'
    | '/settings/notifications'
    | '/settings/voice'
    | '/status/new'
    | '/tasks/$id'
    | '/business/'
    | '/calls/'
    | '/catalog/'
    | '/chat/'
    | '/contacts/'
    | '/finance/'
    | '/ledger/'
    | '/profile/'
    | '/status/'
    | '/tasks/'
    | '/call/prepare/$conversationId'
    | '/api/public/push/actions'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/delete-account'
    | '/download'
    | '/home'
    | '/login'
    | '/onboarding'
    | '/premium'
    | '/privacy'
    | '/register'
    | '/support'
    | '/terms'
    | '/call/$id'
    | '/calls/$id'
    | '/catalog/$id'
    | '/chat/$id'
    | '/contacts/$id'
    | '/contacts/add'
    | '/ledger/$id'
    | '/photo/new'
    | '/prepare/$token'
    | '/settings/calls'
    | '/settings/notifications'
    | '/settings/voice'
    | '/status/new'
    | '/tasks/$id'
    | '/business'
    | '/calls'
    | '/catalog'
    | '/chat'
    | '/contacts'
    | '/finance'
    | '/ledger'
    | '/profile'
    | '/status'
    | '/tasks'
    | '/call/prepare/$conversationId'
    | '/api/public/push/actions'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  id:
    | '__root__'
    | '/'
    | '/delete-account'
    | '/download'
    | '/home'
    | '/login'
    | '/onboarding'
    | '/premium'
    | '/privacy'
    | '/register'
    | '/support'
    | '/terms'
    | '/call/$id'
    | '/calls/$id'
    | '/catalog/$id'
    | '/chat/$id'
    | '/contacts/$id'
    | '/contacts/add'
    | '/ledger/$id'
    | '/photo/new'
    | '/prepare/$token'
    | '/settings/calls'
    | '/settings/notifications'
    | '/settings/voice'
    | '/status/new'
    | '/tasks/$id'
    | '/business/'
    | '/calls/'
    | '/catalog/'
    | '/chat/'
    | '/contacts/'
    | '/finance/'
    | '/ledger/'
    | '/profile/'
    | '/status/'
    | '/tasks/'
    | '/call/prepare/$conversationId'
    | '/api/public/push/actions'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeleteAccountRoute: typeof DeleteAccountRoute
  DownloadRoute: typeof DownloadRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PremiumRoute: typeof PremiumRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  CallIdRoute: typeof CallIdRoute
  CallsIdRoute: typeof CallsIdRoute
  CatalogIdRoute: typeof CatalogIdRoute
  ChatIdRoute: typeof ChatIdRoute
  ContactsIdRoute: typeof ContactsIdRoute
  ContactsAddRoute: typeof ContactsAddRoute
  LedgerIdRoute: typeof LedgerIdRoute
  PhotoNewRoute: typeof PhotoNewRoute
  PrepareTokenRoute: typeof PrepareTokenRoute
  SettingsCallsRoute: typeof SettingsCallsRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsVoiceRoute: typeof SettingsVoiceRoute
  StatusNewRoute: typeof StatusNewRoute
  TasksIdRoute: typeof TasksIdRoute
  BusinessIndexRoute: typeof BusinessIndexRoute
  CallsIndexRoute: typeof CallsIndexRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ContactsIndexRoute: typeof ContactsIndexRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
  LedgerIndexRoute: typeof LedgerIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  StatusIndexRoute: typeof StatusIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  CallPrepareConversationIdRoute: typeof CallPrepareConversationIdRoute
  ApiPublicPushActionsRoute: typeof ApiPublicPushActionsRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/': {
      id: '/business/'
      path: '/business'
      fullPath: '/business/'
      preLoaderRoute: typeof BusinessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call/$id': {
      id: '/call/$id'
      path: '/call/$id'
      fullPath: '/call/$id'
      preLoaderRoute: typeof CallIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls/': {
      id: '/calls/'
      path: '/calls'
      fullPath: '/calls/'
      preLoaderRoute: typeof CallsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls/$id': {
      id: '/calls/$id'
      path: '/calls/$id'
      fullPath: '/calls/$id'
      preLoaderRoute: typeof CallsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/$id': {
      id: '/catalog/$id'
      path: '/catalog/$id'
      fullPath: '/catalog/$id'
      preLoaderRoute: typeof CatalogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/': {
      id: '/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof ContactsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/$id': {
      id: '/contacts/$id'
      path: '/contacts/$id'
      fullPath: '/contacts/$id'
      preLoaderRoute: typeof ContactsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/add': {
      id: '/contacts/add'
      path: '/contacts/add'
      fullPath: '/contacts/add'
      preLoaderRoute: typeof ContactsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/': {
      id: '/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger/': {
      id: '/ledger/'
      path: '/ledger'
      fullPath: '/ledger/'
      preLoaderRoute: typeof LedgerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger/$id': {
      id: '/ledger/$id'
      path: '/ledger/$id'
      fullPath: '/ledger/$id'
      preLoaderRoute: typeof LedgerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo/new': {
      id: '/photo/new'
      path: '/photo/new'
      fullPath: '/photo/new'
      preLoaderRoute: typeof PhotoNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prepare/$token': {
      id: '/prepare/$token'
      path: '/prepare/$token'
      fullPath: '/prepare/$token'
      preLoaderRoute: typeof PrepareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/calls': {
      id: '/settings/calls'
      path: '/settings/calls'
      fullPath: '/settings/calls'
      preLoaderRoute: typeof SettingsCallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/voice': {
      id: '/settings/voice'
      path: '/settings/voice'
      fullPath: '/settings/voice'
      preLoaderRoute: typeof SettingsVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status/': {
      id: '/status/'
      path: '/status'
      fullPath: '/status/'
      preLoaderRoute: typeof StatusIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status/new': {
      id: '/status/new'
      path: '/status/new'
      fullPath: '/status/new'
      preLoaderRoute: typeof StatusNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$id': {
      id: '/tasks/$id'
      path: '/tasks/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof TasksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call/prepare/$conversationId': {
      id: '/call/prepare/$conversationId'
      path: '/call/prepare/$conversationId'
      fullPath: '/call/prepare/$conversationId'
      preLoaderRoute: typeof CallPrepareConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push/actions': {
      id: '/api/public/push/actions'
      path: '/api/public/push/actions'
      fullPath: '/api/public/push/actions'
      preLoaderRoute: typeof ApiPublicPushActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeleteAccountRoute: DeleteAccountRoute,
  DownloadRoute: DownloadRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PremiumRoute: PremiumRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  CallIdRoute: CallIdRoute,
  CallsIdRoute: CallsIdRoute,
  CatalogIdRoute: CatalogIdRoute,
  ChatIdRoute: ChatIdRoute,
  ContactsIdRoute: ContactsIdRoute,
  ContactsAddRoute: ContactsAddRoute,
  LedgerIdRoute: LedgerIdRoute,
  PhotoNewRoute: PhotoNewRoute,
  PrepareTokenRoute: PrepareTokenRoute,
  SettingsCallsRoute: SettingsCallsRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsVoiceRoute: SettingsVoiceRoute,
  StatusNewRoute: StatusNewRoute,
  TasksIdRoute: TasksIdRoute,
  BusinessIndexRoute: BusinessIndexRoute,
  CallsIndexRoute: CallsIndexRoute,
  CatalogIndexRoute: CatalogIndexRoute,
  ChatIndexRoute: ChatIndexRoute,
  ContactsIndexRoute: ContactsIndexRoute,
  FinanceIndexRoute: FinanceIndexRoute,
  LedgerIndexRoute: LedgerIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  StatusIndexRoute: StatusIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  CallPrepareConversationIdRoute: CallPrepareConversationIdRoute,
  ApiPublicPushActionsRoute: ApiPublicPushActionsRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
