revoke execute on function public.set_updated_at() from anon, authenticated, public;
revoke execute on function public.gen_mcm_pin() from anon, authenticated, public;
revoke execute on function public.assign_pin() from anon, authenticated, public;
revoke execute on function public.handle_new_user() from anon, authenticated, public;
revoke execute on function public.bump_conversation() from anon, authenticated, public;
revoke execute on function public.seed_business_owner() from anon, authenticated, public;
revoke execute on function public.is_conv_member(uuid, uuid) from anon, public;
revoke execute on function public.is_call_participant(uuid, uuid) from anon, public;
revoke execute on function public.business_role_of(uuid, uuid) from anon, public;
revoke execute on function public.can_manage_business(uuid, uuid) from anon, public;
revoke execute on function public.can_sell_business(uuid, uuid) from anon, public;
revoke execute on function public.is_business_member(uuid, uuid) from anon, public;
revoke execute on function public.can_see_ledger(uuid, uuid) from anon, public;
revoke execute on function public.record_ledger_payment(uuid, numeric, text, text) from anon, public;
revoke execute on function public.find_profile_by_pin(text) from anon, public;
grant execute on function public.is_conv_member(uuid, uuid) to authenticated;
grant execute on function public.is_call_participant(uuid, uuid) to authenticated;
grant execute on function public.business_role_of(uuid, uuid) to authenticated;
grant execute on function public.can_manage_business(uuid, uuid) to authenticated;
grant execute on function public.can_sell_business(uuid, uuid) to authenticated;
grant execute on function public.is_business_member(uuid, uuid) to authenticated;
grant execute on function public.can_see_ledger(uuid, uuid) to authenticated;
grant execute on function public.record_ledger_payment(uuid, numeric, text, text) to authenticated;
grant execute on function public.find_profile_by_pin(text) to authenticated;